In [2]:
import json
from sqlalchemy import create_engine, Column, Integer, String, Text
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker
DATABASE_URL = "mysql+pymysql://root:123456@localhost:6116/docker-phalapi"
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()
def get_db():
    """获取数据库会话的工具函数"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

In [3]:
json_first_level_keys =['old_material_id','builder_meta', 'nsites', 'elements', 'nelements', 'composition', 'composition_reduced', 'formula_pretty', 'formula_anonymous', 'chemsys', 'volume', 'density', 'density_atomic', 'symmetry', 'material_id', 'deprecated', 'deprecation_reasons', 'last_updated', 'origins', 'warnings', 'structure', 'property_name', 'task_ids', 'uncorrected_energy_per_atom', 'energy_per_atom', 'formation_energy_per_atom', 'energy_above_hull', 'is_stable', 'equilibrium_reaction_energy_per_atom', 'decomposes_to', 'xas', 'grain_boundaries', 'band_gap', 'cbm', 'vbm', 'efermi', 'is_gap_direct', 'is_metal', 'es_source_calc_id', 'bandstructure', 'dos', 'dos_energy_up', 'dos_energy_down', 'is_magnetic', 'ordering', 'total_magnetization', 'total_magnetization_normalized_vol', 'total_magnetization_normalized_formula_units', 'num_magnetic_sites', 'num_unique_magnetic_sites', 'types_of_magnetic_species', 'bulk_modulus', 'shear_modulus', 'universal_anisotropy', 'homogeneous_poisson', 'e_total', 'e_ionic', 'e_electronic', 'n', 'e_ij_max', 'weighted_surface_energy_EV_PER_ANG2', 'weighted_surface_energy', 'weighted_work_function', 'surface_anisotropy', 'shape_factor', 'has_reconstructed', 'possible_species', 'has_props', 'theoretical', 'database_IDs', 'fields_not_requested','set_time']
class MaterialPJ(Base):
    __tablename__ = "MaterialPJ"  # 表名
    # __table_args__ = {'extend_existing': True}
    
    id = Column(Integer, primary_key=True,index= True)  
    for key in json_first_level_keys:
        if key in ["builder_meta","bandstructure", "dos", "structure", "origins","database_IDs","symmetry","warnings","task_ids","xas",'has_props']:
            locals()[key] = Column(Text, nullable=True)
        elif key in ["material_id", "old_material_id", "chemsys", "formula_pretty","nsites","nelements","deprecated","is_stable"]:
            locals()[key] = Column(String(50), nullable=True)
        else:
            locals()[key] = Column(String(200), nullable=True)
    # 清理局部变量，避免冗余
    del key

In [4]:

def query_material_by_old_id(old_material_id):
    db = next(get_db())
    try:
        material = db.query(MaterialPJ).filter(MaterialPJ.old_material_id == old_material_id).first()
        return material
    finally:
        db.close()


In [31]:
from pymatgen.core import Structure,Element
# 执行查询
Material_id="mp-1180433"
result = query_material_by_old_id(Material_id)
print("查询结束")
structure = json.loads(result.structure)
structure1 = Structure.from_dict(structure)

查询结束


In [32]:
print(result.structure)

{"@module": "pymatgen.core.structure", "@class": "Structure", "charge": 0, "lattice": {"matrix": [[3.513338999999999, 0.0, 0.0], [0.0, 6.253102, 0.0], [0.0, 0.0, 13.062496]], "pbc": [true, true, true], "a": 3.513338999999999, "b": 6.253102, "c": 13.062496, "alpha": 90.0, "beta": 90.0, "gamma": 90.0, "volume": 286.973463976919}, "properties": {}, "sites": [{"species": [{"element": "Nd", "occu": 1}], "abc": [0.7618900000000001, 0.737568999999999, 0.25], "properties": {"magmom": 0.014}, "label": "Nd", "xyz": [2.6767778507099993, 4.612094189037994, 3.265624]}, {"species": [{"element": "Nd", "occu": 1}], "abc": [0.73811, 0.237569, 0.25], "properties": {"magmom": 0.014}, "label": "Nd", "xyz": [2.5932306492899992, 1.485543189038, 3.265624]}, {"species": [{"element": "Nd", "occu": 1}], "abc": [0.26189, 0.762431, 0.75], "properties": {"magmom": 0.014}, "label": "Nd", "xyz": [0.9201083507099997, 4.767558810962, 9.796872]}, {"species": [{"element": "Nd", "occu": 1}], "abc": [0.23811000000000002, 

In [ ]:
structure1.to(filename="mp-19770.cif", fmt="cif", symprec=0.1)

In [35]:
import numpy as np
cart = np.asarray(structure1.cart_coords, dtype=float)
print(cart)
print(len(cart))

[[ 2.67677785  4.61209419  3.265624  ]
 [ 2.59323065  1.48554319  3.265624  ]
 [ 0.92010835  4.76755881  9.796872  ]
 [ 0.83656115  1.64100781  9.796872  ]
 [ 1.7566695   3.126551    6.531248  ]
 [ 0.          0.          0.        ]
 [ 1.7566695   3.126551    0.        ]
 [ 0.          0.          6.531248  ]
 [ 1.15251573  1.18738903  7.49147208]
 [ 0.60415377  4.31394003  7.49147208]
 [ 2.90918523  1.93916197  0.96022408]
 [ 0.91079449  3.14132708  3.265624  ]
 [ 2.66746399  6.23832592  9.796872  ]
 [ 2.36082327  5.06571297  5.57102392]
 [ 0.84587501  0.01477608  3.265624  ]
 [ 2.90918523  1.93916197  5.57102392]
 [ 2.36082327  5.06571297  0.96022408]
 [ 0.60415377  4.31394003 12.10227192]
 [ 2.60254451  3.11177492  9.796872  ]
 [ 1.15251573  1.18738903 12.10227192]]
20


In [37]:
syms = [str(site.specie) for site in structure1.sites]
print(syms)

['Nd', 'Nd', 'Nd', 'Nd', 'Fe', 'Fe', 'Fe', 'Fe', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']


In [38]:
from collections import defaultdict
groups = defaultdict(list)
for idx, sym in enumerate(syms):
    groups[sym].append(idx)
groups

defaultdict(list,
            {'Nd': [0, 1, 2, 3],
             'Fe': [4, 5, 6, 7],
             'O': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]})

In [79]:
from pymatgen.analysis.local_env import CrystalNN
coords = np.asarray(np.round(structure1.cart_coords, 6), dtype=float)
n = len(coords)
cnn = CrystalNN()
pts = []
lines = []

for i in range(n):
    for info in cnn.get_nn_info(structure1, i):
        j = info["site_index"]
        p1 = coords[i]
        
        # 2. 正确获取配位原子的笛卡尔坐标（而非分数坐标），并统一精度
        p2 = np.asarray(np.round(info["site"].coords, 6), dtype=float)
        
        # 3. 正确判断 p2 是否在 coords 中（检查是否有某一行与 p2 完全相等）
        # np.all(coords == p2, axis=1) → 每行是否全等于 p2（返回布尔数组）
        # np.any(...) → 是否存在这样的行
        if np.any(np.all(coords == p2, axis=1)):
            if j > i:  # 去重
                idx0 = len(pts)
                pts.append(p1)
                pts.append(p2)
                lines.extend([2, idx0, idx0 + 1])
        else:
            continue
# if not pts:
#     return None
# 
# poly = pv.PolyData()
# poly.points = np.array(pts, dtype=float)
# poly.lines  = np.array(lines, dtype=int)
# return poly.tube(radius=bond_radius, n_sides=16)

In [80]:
# print(coords)
structure1.cart_coords

array([[ 2.67677785,  4.61209419,  3.265624  ],
       [ 2.59323065,  1.48554319,  3.265624  ],
       [ 0.92010835,  4.76755881,  9.796872  ],
       [ 0.83656115,  1.64100781,  9.796872  ],
       [ 1.7566695 ,  3.126551  ,  6.531248  ],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.7566695 ,  3.126551  ,  0.        ],
       [ 0.        ,  0.        ,  6.531248  ],
       [ 1.15251573,  1.18738903,  7.49147208],
       [ 0.60415377,  4.31394003,  7.49147208],
       [ 2.90918523,  1.93916197,  0.96022408],
       [ 0.91079449,  3.14132708,  3.265624  ],
       [ 2.66746399,  6.23832592,  9.796872  ],
       [ 2.36082327,  5.06571297,  5.57102392],
       [ 0.84587501,  0.01477608,  3.265624  ],
       [ 2.90918523,  1.93916197,  5.57102392],
       [ 2.36082327,  5.06571297,  0.96022408],
       [ 0.60415377,  4.31394003, 12.10227192],
       [ 2.60254451,  3.11177492,  9.796872  ],
       [ 1.15251573,  1.18738903, 12.10227192]])

In [81]:
print(pts)

[array([2.676778, 4.612094, 3.265624]), array([0.910794, 3.141327, 3.265624]), array([2.676778, 4.612094, 3.265624]), array([2.360823, 5.065713, 0.960224]), array([2.676778, 4.612094, 3.265624]), array([2.360823, 5.065713, 5.571024]), array([2.593231, 1.485543, 3.265624]), array([0.845875, 0.014776, 3.265624]), array([2.593231, 1.485543, 3.265624]), array([2.909185, 1.939162, 5.571024]), array([2.593231, 1.485543, 3.265624]), array([2.909185, 1.939162, 0.960224]), array([2.593231, 1.485543, 3.265624]), array([0.910794, 3.141327, 3.265624]), array([0.920108, 4.767559, 9.796872]), array([2.667464, 6.238326, 9.796872]), array([0.920108, 4.767559, 9.796872]), array([0.604154, 4.31394 , 7.491472]), array([0.920108, 4.767559, 9.796872]), array([ 0.604154,  4.31394 , 12.102272]), array([0.920108, 4.767559, 9.796872]), array([2.602545, 3.111775, 9.796872]), array([0.836561, 1.641008, 9.796872]), array([2.602545, 3.111775, 9.796872]), array([0.836561, 1.641008, 9.796872]), array([ 1.152516,  1.

In [82]:
# 将 pts 中的每个 numpy 数组转为元组（保留足够精度，避免浮点数误差）
pts_tuples = [tuple(np.round(coord, 6)) for coord in pts]  # 保留6位小数

# 转换为集合去重
unique_pts = set(pts_tuples)

# 打印结果（可选：转回列表或数组以便后续使用）
print(len(unique_pts))
print(unique_pts)

19
{(np.float64(0.604154), np.float64(4.31394), np.float64(12.102272)), (np.float64(0.845875), np.float64(0.014776), np.float64(3.265624)), (np.float64(2.602545), np.float64(3.111775), np.float64(9.796872)), (np.float64(0.604154), np.float64(4.31394), np.float64(7.491472)), (np.float64(0.836561), np.float64(1.641008), np.float64(9.796872)), (np.float64(2.909185), np.float64(1.939162), np.float64(0.960224)), (np.float64(0.920108), np.float64(4.767559), np.float64(9.796872)), (np.float64(2.593231), np.float64(1.485543), np.float64(3.265624)), (np.float64(2.360823), np.float64(5.065713), np.float64(5.571024)), (np.float64(2.676778), np.float64(4.612094), np.float64(3.265624)), (np.float64(1.152516), np.float64(1.187389), np.float64(12.102272)), (np.float64(2.360823), np.float64(5.065713), np.float64(0.960224)), (np.float64(1.152516), np.float64(1.187389), np.float64(7.491472)), (np.float64(1.756669), np.float64(3.126551), np.float64(0.0)), (np.float64(0.0), np.float64(0.0), np.float64(6.5

In [54]:
pts_tuples2 = set([tuple(np.round(coord, 6)) for coord in coords])

In [57]:
pts3=unique_pts-pts_tuples2
print(len(pts3))
print(pts3)

16
{(np.float64(-0.845875), np.float64(6.238326), np.float64(9.796872)), (np.float64(2.667464), np.float64(-0.014776), np.float64(9.796872)), (np.float64(-0.845875), np.float64(-0.014776), np.float64(9.796872)), (np.float64(-0.604154), np.float64(1.939162), np.float64(0.960224)), (np.float64(0.604154), np.float64(-1.939162), np.float64(-0.960224)), (np.float64(-0.604154), np.float64(1.939162), np.float64(5.571024)), (np.float64(0.604154), np.float64(-1.939162), np.float64(7.491472)), (np.float64(-1.152516), np.float64(-1.187389), np.float64(0.960224)), (np.float64(0.845875), np.float64(6.267878), np.float64(3.265624)), (np.float64(4.359214), np.float64(0.014776), np.float64(3.265624)), (np.float64(-0.910794), np.float64(3.111775), np.float64(9.796872)), (np.float64(1.152516), np.float64(1.187389), np.float64(-0.960224)), (np.float64(4.359214), np.float64(6.267878), np.float64(3.265624)), (np.float64(4.424133), np.float64(3.141327), np.float64(3.265624)), (np.float64(-1.152516), np.floa

In [64]:
x=[i for i in pts3 if i in np.asarray(np.round(coords, 6))]
print(x)
print(len(x))
print(np.asarray(np.round(coords, 6)))

[(np.float64(-0.845875), np.float64(6.238326), np.float64(9.796872)), (np.float64(2.667464), np.float64(-0.014776), np.float64(9.796872)), (np.float64(-0.845875), np.float64(-0.014776), np.float64(9.796872)), (np.float64(-0.604154), np.float64(1.939162), np.float64(0.960224)), (np.float64(0.604154), np.float64(-1.939162), np.float64(-0.960224)), (np.float64(-0.604154), np.float64(1.939162), np.float64(5.571024)), (np.float64(0.604154), np.float64(-1.939162), np.float64(7.491472)), (np.float64(-1.152516), np.float64(-1.187389), np.float64(0.960224)), (np.float64(0.845875), np.float64(6.267878), np.float64(3.265624)), (np.float64(4.359214), np.float64(0.014776), np.float64(3.265624)), (np.float64(-0.910794), np.float64(3.111775), np.float64(9.796872)), (np.float64(1.152516), np.float64(1.187389), np.float64(-0.960224)), (np.float64(4.359214), np.float64(6.267878), np.float64(3.265624)), (np.float64(4.424133), np.float64(3.141327), np.float64(3.265624)), (np.float64(-1.152516), np.float64

In [66]:
coords_tuples = set(tuple(coord) for coord in np.round(coords, 6))
x = [i for i in pts3 if i in coords_tuples]
print(coords_tuples)
print(x)  # 此时仅包含真正数值匹配的元素
print(len(x))

{(np.float64(0.604154), np.float64(4.31394), np.float64(12.102272)), (np.float64(0.845875), np.float64(0.014776), np.float64(3.265624)), (np.float64(2.602545), np.float64(3.111775), np.float64(9.796872)), (np.float64(0.604154), np.float64(4.31394), np.float64(7.491472)), (np.float64(0.836561), np.float64(1.641008), np.float64(9.796872)), (np.float64(2.909185), np.float64(1.939162), np.float64(0.960224)), (np.float64(0.920108), np.float64(4.767559), np.float64(9.796872)), (np.float64(2.593231), np.float64(1.485543), np.float64(3.265624)), (np.float64(2.360823), np.float64(5.065713), np.float64(5.571024)), (np.float64(2.676778), np.float64(4.612094), np.float64(3.265624)), (np.float64(1.152516), np.float64(1.187389), np.float64(12.102272)), (np.float64(0.0), np.float64(0.0), np.float64(0.0)), (np.float64(2.360823), np.float64(5.065713), np.float64(0.960224)), (np.float64(1.756669), np.float64(3.126551), np.float64(0.0)), (np.float64(0.0), np.float64(0.0), np.float64(6.531248)), (np.float

In [40]:
print(coords)

[[ 2.67677785  4.61209419  3.265624  ]
 [ 2.59323065  1.48554319  3.265624  ]
 [ 0.92010835  4.76755881  9.796872  ]
 [ 0.83656115  1.64100781  9.796872  ]
 [ 1.7566695   3.126551    6.531248  ]
 [ 0.          0.          0.        ]
 [ 1.7566695   3.126551    0.        ]
 [ 0.          0.          6.531248  ]
 [ 1.15251573  1.18738903  7.49147208]
 [ 0.60415377  4.31394003  7.49147208]
 [ 2.90918523  1.93916197  0.96022408]
 [ 0.91079449  3.14132708  3.265624  ]
 [ 2.66746399  6.23832592  9.796872  ]
 [ 2.36082327  5.06571297  5.57102392]
 [ 0.84587501  0.01477608  3.265624  ]
 [ 2.90918523  1.93916197  5.57102392]
 [ 2.36082327  5.06571297  0.96022408]
 [ 0.60415377  4.31394003 12.10227192]
 [ 2.60254451  3.11177492  9.796872  ]
 [ 1.15251573  1.18738903 12.10227192]]


In [42]:
info=cnn.get_nn_info(structure1, 0)
print(info.get("site").coords)

AttributeError: 'list' object has no attribute 'get'

In [30]:
info=cnn.get_nn_info(structure1, 0)[4]
il=np.asarray(info.get("site").coords, dtype=float)
xdj=il==coords[6]
if il in coords:
    print("True")
else:
    print("False")
# print()

False


In [16]:
cnn.get_nn_info(structure1, 1)

[{'site': PeriodicNeighbor: O (-0.782, 4.433, 0.1831) [-0.25, 0.25, 0.5554],
  'image': (np.float64(-1.0), np.float64(0.0), np.float64(0.0)),
  'weight': 1,
  'site_index': np.int64(7)},
 {'site': PeriodicNeighbor: O (-3.279, 6.069, 0.9042) [0.05542, 0.25, 1.25],
  'image': (np.float64(0.0), np.float64(0.0), np.float64(1.0)),
  'weight': 1,
  'site_index': np.int64(6)},
 {'site': PeriodicNeighbor: O (-3.039, 3.149, 1.823) [0.4447, 0.25, 0.9446],
  'image': (np.float64(0.0), np.float64(0.0), np.float64(0.0)),
  'weight': 1,
  'site_index': np.int64(8)},
 {'site': PeriodicNeighbor: O (-0.4742, 3.96, 2.909) [0.25, 0.75, 0.4446],
  'image': (np.float64(0.0), np.float64(0.0), np.float64(0.0)),
  'weight': 1,
  'site_index': np.int64(5)},
 {'site': PeriodicNeighbor: O (-0.8513, 6.528, 2.188) [-0.05541, 0.75, 0.75],
  'image': (np.float64(-1.0), np.float64(0.0), np.float64(0.0)),
  'weight': 1,
  'site_index': np.int64(9)},
 {'site': PeriodicNeighbor: O (-2.73, 5.244, 3.63) [0.5554, 0.75, 1.0

In [12]:
print(pts)
print(lines)

[array([-2.33139513,  1.49058522,  1.0365999 ]), array([-0.4049853 ,  1.86523274,  0.90371347]), array([-2.33139513,  1.49058522,  1.0365999 ]), array([-2.42087962,  0.22951593,  2.54379076]), array([-2.33139513,  1.49058522,  1.0365999 ]), array([-3.03905181,  3.14910585,  1.82302324]), array([-2.33139513,  1.49058522,  1.0365999 ]), array([-2.49013538,  2.32425347,  4.54888002]), array([-2.33139513,  1.49058522,  1.0365999 ]), array([0.14392318, 1.04039821, 3.6295757 ]), array([-2.33139513,  1.49058522,  1.0365999 ]), array([-0.47423127,  3.95998901,  2.90876873]), array([-1.9895329 ,  4.80759906,  1.68995955]), array([-2.42087962,  0.22951593,  2.54379076]), array([-1.9895329 ,  4.80759906,  1.68995955]), array([-0.4049853 ,  1.86523274,  0.90371347]), array([-1.9895329 ,  4.80759906,  1.68995955]), array([-3.03905181,  3.14910585,  1.82302324]), array([-1.9895329 ,  4.80759906,  1.68995955]), array([-0.47423127,  3.95998901,  2.90876873]), array([-1.9895329 ,  4.80759906,  1.689959

In [19]:
# 将 pts 中的每个 numpy 数组转为元组（保留足够精度，避免浮点数误差）
pts_tuples = [tuple(np.round(coord, 6)) for coord in pts]  # 保留6位小数

# 转换为集合去重
unique_pts = set(pts_tuples)

# 打印结果（可选：转回列表或数组以便后续使用）
print(len(unique_pts))


10
